# Generated by Django 3.0.8 on 2020-07-11 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cari',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hesapKodu', models.CharField(max_length=20)),
                ('unvan', models.CharField(max_length=80)),
                ('ad', models.CharField(blank=True, max_length=40, null=True)),
                ('soyad', models.CharField(blank=True, max_length=40, null=True)),
                ('aktifPasif', models.IntegerField(blank=True, choices=[(0, 'Aktif'), (1, 'Pasif')], null=True)),
                ('bakGostSekli', models.IntegerField(blank=True, choices=[(0, 'Yerel Para'), (1, 'Doviz'), (2, '2005 öncesi TL')], null=True)),
                ('dvzTL', models.IntegerField(blank=True, choices=[(0, 'Yerel Para'), (1, 'Doviz'), (2, 'Doviz Yerel Para')], null=True)),
                ('dovizCinsi', models.CharField(blank=True, max_length=3, null=True)),
                ('dovizIslemKurCins', models.IntegerField(blank=True, choices=[(0, 'Merkez Bankasi Alis'), (1, 'Merkez Bankasi Satis'), (2, 'Merkez Bankasi Efektif Alis'), (3, 'Merkez Bankasi Efektif Satis'), (4, 'EUR CaprazKur'), (5, 'USD Capraz Kur')], null=True)),
                ('krediLimiti', models.IntegerField(blank=True, null=True)),
                ('dvzKrediLimiti', models.IntegerField(blank=True, null=True)),
                ('bolgeKod', models.CharField(blank=True, max_length=4, null=True)),
                ('ozelKod', models.CharField(blank=True, max_length=20, null=True)),
                ('grupKod', models.CharField(blank=True, max_length=20, null=True)),
                ('tipKod', models.CharField(blank=True, max_length=20, null=True)),
                ('mhsKod', models.CharField(blank=True, max_length=20, null=True)),
                ('masrafMerkezi', models.CharField(blank=True, max_length=20, null=True)),
                ('resim', models.ImageField(blank=True, default='Static/pics/cari_pic/none/no-img.jpg', null=True, upload_to='Static/pics/cari_pic')),
                ('vergiDairesi', models.CharField(blank=True, max_length=20, null=True)),
                ('hesapNo', models.CharField(blank=True, max_length=20, null=True)),
                ('faturaChk', models.CharField(blank=True, max_length=20, null=True)),
                ('iskontoOran', models.IntegerField(blank=True, null=True)),
                ('opsiyonGunu', models.IntegerField(blank=True, null=True)),
                ('odemeGunu', models.IntegerField(blank=True, choices=[(0, 'Belirsiz'), (1, 'Pazartesi'), (2, 'Salı'), (3, 'Çarşamba'), (4, 'Perşembe'), (5, 'Cuma'), (6, 'Cumartesi'), (7, 'Pazar')], null=True)),
                ('odemePlani', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('kulSatisFiyat', models.IntegerField(blank=True, choices=[(0, 'Satiş Fiyatı 1'), (1, 'Satış Fiyatı 2'), (2, 'Satış Fiyatı 3'), (3, 'Satış Fiyatı 4'), (4, 'Satış Fiyatı 5'), (5, 'Satış Fiyatı 6'), (6, 'Döviz Satış Fiyatı 1'), (7, 'Döviz Satış Fiyatı 2'), (8, 'Döviz Satış Fiyatı 3'), (9, 'Alış Fiyatı 1'), (10, 'Alış Fiyatı 2'), (11, 'Alış Fiyatı 3'), (12, 'Döviz Alış Fiyatı 1'), (13, 'Döviz Alış Fiyatı 2'), (14, 'Döviz Alış Fiyatı 3')], null=True)),
                ('chKodu', models.CharField(blank=True, max_length=20, null=True)),
                ('kdvTevfikatUygula', models.BooleanField(blank=True, null=True)),
                ('kdvMuaf', models.BooleanField(blank=True, null=True)),
                ('kdvMuafAck', models.CharField(blank=True, max_length=20, null=True)),
                ('formBaBsUnvan', models.BooleanField(blank=True, null=True)),
                ('sirketEMail', models.EmailField(blank=True, max_length=50, null=True)),
                ('sirketWebAdres', models.CharField(blank=True, max_length=50, null=True)),
                ('satIslemEMail', models.EmailField(blank=True, max_length=50, null=True)),
                ('satAlmaIslemEMail', models.EmailField(blank=True, max_length=50, null=True)),
                ('finIslemEMail', models.EmailField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Cari',
            },
        ),
        migrations.CreateModel(
            name='CariAdres',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('AdresTipi', models.IntegerField(blank=True, null=True)),
                ('AdresBaslik', models.CharField(max_length=50)),
                ('AdresUlkeKod', models.CharField(blank=True, max_length=20, null=True)),
                ('AdresUlkeNumKod', models.CharField(blank=True, max_length=20, null=True)),
                ('AdresSehir', models.CharField(blank=True, max_length=40, null=True)),
                ('AdresIlce', models.CharField(blank=True, max_length=40, null=True)),
                ('AdresKasabaKoy', models.CharField(blank=True, max_length=40, null=True)),
                ('AdresCadde', models.CharField(blank=True, max_length=40, null=True)),
                ('AdresBinaAdi', models.CharField(blank=True, max_length=40, null=True)),
                ('AdresDisKapiNo', models.CharField(blank=True, max_length=10, null=True)),
                ('AdresIcKapiNo', models.CharField(blank=True, max_length=10, null=True)),
                ('AdresPKod', models.CharField(blank=True, max_length=70, null=True)),
                ('CariID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altProje.Cari')),
            ],
            options={
                'db_table': 'CariAdres',
            },
        ),
    ]
